apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hack-istio-instruments
  name: bass2
  labels:
    app: bass2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bass2
  template:
    metadata:
      labels:
        app: bass2
    spec:
      serviceAccountName: instruments-sa
      containers:
        - name: bass2
          image: gregerrag/istio-instrument
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: Europe/Zurich
            - name: INSTRUMENT_ID
              value: "bass2"
---
apiVersion: v1
kind: Service
metadata:
  name: bass2
  namespace: hack-istio-instruments
spec:
  selector:
    app: bass2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080