apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hack-istio-instruments
  name: hh1
  labels:
    app: hh1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hh
      type: hh1
  template:
    metadata:
      labels:
        app: hh
        type: hh1
    spec:
      serviceAccountName: instruments-sa
      containers:
        - name: hh1
          image: gregerrag/istio-instrument
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: Europe/Zurich
            - name: INSTRUMENT_ID
              value: "hh1"