apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hack-istio-instruments
  name: piano1
  labels:
    app: piano1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: piano
      type: piano1
  template:
    metadata:
      labels:
        app: piano
        type: piano1
    spec:
      serviceAccountName: instruments-sa
      containers:
        - name: piano1
          image: gregerrag/istio-instrument
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: Europe/Zurich
            - name: INSTRUMENT_ID
              value: "piano1"